### ISSUE TITLE
webview支持太差了，打开空白

### ISSUE THREAD

**Issue by oppfx** [cryptape/neuron-android#68]
http://dapp.cryptape.com:8080 打开空白，对页面支持不友好，建议加入Chrome内核的webview

**Comment by duanyytop** [comment]
官方webview就是基于Chrome内核，只是我们这个demo是基于ES6开发的，在Android 7.0以下的系统上会存在兼容性问题，所以会出现空白的现象。考虑到 First Forever 只是一个demo，所以我们并没有处理太多兼容性的问题
